OpenAPI-Qraft/openapi-qraft

.changeset/thick-kids-double.md, packages/cli/src/lib/ts-factory/getClientFactory.ts, packages/react-client/README.md, packages/react-client/src/ServiceOperation.ts, packages/react-client/src/callbacks/cancelQueries.ts, packages/react-client/src/callbacks/invalidateQueries.ts, packages/react-client/src/lib/callQueryClientMethodWithQueryFilters.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx, playground/src/App.tsx
Add support for `QueryClient` method `cancelQueries(...)`.
Example: 
```ts
qraft.pet.getPetById.cancelQueries(
{ parameters: { path: { petId } } },
queryClient
)
```
=> feat: Query Cancellation support

packages/cli/README.md, packages/cli/src/bin.ts, website/docs/codegen/cli.mdx
Added `--service-name-base <endpoint | tags>` documentation.
=> docs(cli): add documentation to `--service-name-base` option

packages/cli/src/lib/open-api/__fixtures__/openapi.json, packages/cli/src/lib/open-api/__snapshots__/getServices.spec.ts.snap, packages/cli/src/lib/open-api/getServices.spec.ts
Added `getServices(...)` tests to cover `serviceNameBase: endpoint | tags` option
=> chore(cli): update `getServices(...)` tests

.changeset/tidy-walls-fix.md, packages/cli/README.md, packages/cli/package.json, packages/cli/src/bin.ts, packages/cli/src/lib/open-api/__snapshots__/getServices.spec.ts.snap, packages/cli/src/lib/open-api/getServiceName.spec.ts, packages/cli/src/lib/open-api/getServiceName.ts, packages/cli/src/lib/open-api/getServiceNamesByEndpoint.spec.ts, packages/cli/src/lib/open-api/getServiceNamesByOperationEndpoint.ts, packages/cli/src/lib/open-api/getServiceNamesByOperationTags.spec.ts, packages/cli/src/lib/open-api/getServiceNamesByOperationTags.ts, packages/cli/src/lib/open-api/getServices.spec.ts, packages/cli/src/lib/open-api/getServices.ts, website/docs/codegen/cli.mdx
Added support for specifying a specific segment of an OpenAPI Operation's endpoint path (as a Services group) by using the `--service-name-base endpoint[<index>]` option. This update allows more granular control over service naming based on individual path segments.
Removed the previous default behavior that only allowed using the first segment of the endpoint path with `--service-name-base endpoint`.
This change enables customization of the base name for service generation based on different endpoint segments.
=> feat(cli): configurable service basename by endpoint

.github/workflows/deploy-gh-pages.yml
Preventing Documentation Website from being deployed if no changes have been made to the site.
=> chore(website): add `paths` to the "Deploy to GitHub Pages" workflow

.changeset/funny-terms-pretend.md, .changeset/pre.json, packages/openapi-typescript-plugin/src/plugin.ts
This change removes the `.ts` extension from import paths by default when using the OpenAPI TypeScript plugin. This behavior can be overridden for the `@openapi-qraft/tanstack-query-react-plugin` using the `--openapi-types-import-path <path>` option, which allows specifying the full import path, including the `.ts` extension.
=> fix(openapi-typescript-plugin): remove `.ts` extension from import paths by default

.changeset/nice-ladybugs-act.md, packages/tanstack-query-react-plugin/src/__snapshots__/services/ApprovalPoliciesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/getServiceFactory.ts
This PR removes `as const` from the `services` variable to ensure compatibility with older TypeScript versions. This change prevents potential errors and improves the library's accessibility.
=> fix(tanstack-query-react-plugin): remove `as const` from `services`

.changeset/chilled-bobcats-sip.md, packages/tanstack-query-react-plugin/src/__snapshots__/services/ApprovalPoliciesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/getServiceFactory.ts
This PR refactors the service output type to a flatter structure. This change primarily aims to:
* **Improve TypeScript compilation:** The previous nested structure posed challenges for TypeScript compilation, especially when distributing the code as a library.
=> feat: improve service output type for library distribution

.changeset/friendly-schools-learn.md, packages/react-client/package.json, packages/react-client/tsconfig.build.json, packages/react-client/tsup.config.ts
This PR improves the maintainability of our TypeScript type definitions. Instead of having separate `d.ts` files for each module format (ESM, CJS), we now generate all definitions from a single source `d.ts` file. This ensures consistency across module formats and reduces the possibility of discrepancies between the definitions.
=> chore(react-client): Use a single source `d.ts` file for all module formats

.changeset/great-balloons-own.md, packages/react-client/src/callbacks/useMutation.ts, packages/react-client/src/callbacks/useQueries.ts, packages/react-client/src/callbacks/useSuspenseQueries.ts, packages/react-client/src/lib/useComposeUseQueryOptions.ts
Make `requestFn` optional if `queryFn` or `mutationFn` is specified in hooks.
=> feat: make `requestFn` optional

.changeset/fuzzy-pugs-grow.md, .changeset/gorgeous-wasps-trade.md, .changeset/pretty-carrots-kick.md, packages/cli/package.json, packages/openapi-typescript-plugin/package.json, packages/plugin/package.json, packages/react-client/package.json, packages/react-client/src/callbacks/useQueries.ts, packages/react-client/src/callbacks/useSuspenseQueries.ts, packages/react-client/src/service-operation/ServiceOperation.ts, packages/react-client/src/service-operation/ServiceOperationUseInfiniteQuery.ts, packages/react-client/src/service-operation/ServiceOperationUseQueries.ts, packages/react-client/src/service-operation/ServiceOperationUseQuery.ts, packages/react-client/src/service-operation/ServiceOperationUseSuspenseInfiniteQuery.ts, packages/react-client/src/service-operation/ServiceOperationUseSuspenseQueries.ts, packages/react-client/src/service-operation/ServiceOperationUseSuspenseQuery.ts, packages/react-client/src/service-operation/ServiceOperationUseSuspenseQueryQuery.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx, packages/rollup-config/package.json, packages/tanstack-query-react-plugin/package.json
This PR addresses several typing-related issues in the `@openapi-graft/react`:
1. Fixed output type for:
- `useQueries(...)`
- `useSuspenseQueries(...)`
2. Improved typing for `select(...)` function in:
- `useQuery(...)` and `useSuspenseQuery`
- `useInfiniteQuery(...)` and `useSuspenseInfiniteQuery(...)`
=> fix(`@openapi-graft/react package`): typing issues

.changeset/fast-hornets-repeat.md, .changeset/giant-chairs-occur.md, .changeset/pre.json, packages/openapi-typescript-plugin/src/__snapshots__/no-extra-options.ts.snapshot.ts, packages/openapi-typescript-plugin/src/__snapshots__/with-extra-options.ts.snapshot.ts, packages/plugin/src/lib/open-api/__snapshots__/getServices.spec.ts.snap, packages/react-client/src/lib/AreAllOptional.ts, packages/react-client/src/service-operation/ServiceOperationUseMutation.ts, packages/react-client/src/service-operation/ServiceOperationUseQuery.ts, packages/react-client/src/tests/msw/handlers.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts, packages/test-fixtures/openapi.json
This PR introduces improvements to both the `userQuery` and `useMutation` functions to enhance their flexibility and usability:
1. **Improvement to `userQuery`**:
- `userQuery()` can now be called without `{}` as the first argument if all parameters are optional or no parameters are required.
2. **Improvement to `useMutation`**:
- `useMutation` now supports calling `mutate()` or `mutateAsync()` without arguments if body or parameters are optional or `undefined`.
These changes aim to simplify the usage of these functions, making them more intuitive and reducing the need for unnecessary argument passing.
=> feat: no arguments for `useQuery()` and `mutate()`

.github/workflows/versioning.yml
Removed concurrency and production environment usage from the `versioning.yaml` workflow.
=> chore: remove concurrency and production environment from versioning workflow

packages/react-client/src/lib/requestFn.ts, packages/react-client/src/lib/urlSerializer.test.ts
Added tests to ensure URL serialization aligns with RFC 6570.
Reference: https://datatracker.ietf.org/doc/html/rfc6570
=> chore: add `urlSerializer(...)` tests

.changeset/config.json, .changeset/purple-kids-thank.md, .github/workflows/ci.yml, .github/workflows/release.yml, packages/cli/CHANGELOG.md, packages/cli/package.json, packages/openapi-typescript-plugin/CHANGELOG.md, packages/openapi-typescript-plugin/package.json, packages/plugin/.gitignore, packages/plugin/CHANGELOG.md, packages/plugin/package.json, packages/plugin/src/lib/QraftCommand.ts, packages/react-client/CHANGELOG.md, packages/react-client/package.json, packages/tanstack-query-react-plugin/CHANGELOG.md, packages/tanstack-query-react-plugin/package.json, turbo.json, write-package-version-file.sh
Simplified the method for retrieving the package version by transitioning to a more straightforward approach. Instead of dynamically importing or reading directly from `package.json`, the version is now generated in advance and stored in a dedicated file. This change improves maintainability and ensures better compatibility across different Node.js versions, specifically 18, 20, and 22.
=> fix: simplify package version retrieval for enhanced Node.js compatibility

.changeset/rare-bats-rest.md, packages/plugin/src/lib/parseOperationGlobs.ts
In this update, the `sort()` method has been used instead of `toSorted()`. The decision to use `sort()` ensures broader compatibility across different Node.js environments.
=> feat: add Node.js 18.18.0 compatibility

packages/react-client/src/lib/requestFn.ts
Removed the `process.env` check from the `requestFn` function to improve compatibility with ESM.
=> chore: remove `process.env` check from the `requestFn`

packages/plugin/CHANGELOG.md
Fixes a typo in the changelog where `--operation-predefined-parameters` was incorrectly listed. It has been corrected to `--operation-name-modifier`. The changes ensure that the documentation accurately reflects the available options for modifying operation names.
=> chore: fix changelog

packages/react-client/README.md, website/docs/getting-started/quick-start.mdx, website/versioned_docs/version-1.x/getting-started/quick-start.mdx
Added `npm @openapi-qraft/cli@next` instructions.
=> docs(website): fix quick start instructions for the new version

.changeset/sharp-wolves-nail.md, .github/actions/spelling/expect.txt, packages/react-client/src/qraftPredefinedParametersRequestFn.ts, packages/react-client/src/tests/createPredefinedParametersRequestFn.test.ts
Refined all types related to `value` in the `qraftPredefinedParametersRequestFn` function to improve type safety and ensure correct handling of asynchronous values. 
This change introduces `QraftPredefinedParameterResolvedValue`, which better reflects the types of resolved values, and fixes potential issues with function and promise handling.
=> fix(client-react): refine types related `qraftPredefinedParametersRequestFn(...)`

.changeset/purple-pumpkins-mix.md, packages/react-client/src/service-operation/ServiceOperationGetQueryState.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx
Updated the `getQueryState` function to support being invoked without parameters if they are not required. This enhancement simplifies the usage in scenarios where the parameters are optional, providing a more flexible API.
=> feat(react-client): allow `getQueryState(...)` to be called without `parameters`

.changeset/wise-feet-fry.md, .github/workflows/deploy-gh-pages.yml, packages/react-client/src/service-operation/ServiceOperationUseMutation.ts, packages/react-client/src/service-operation/ServiceOperationUseQuery.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx
Restricted `getQueryKey(...)` and `getMutationKey(...)` input types to ensure correct variable usage.
=> fix(react-client): restrict input types for `getQueryKey` and `getMutationKey` to ensure type safety

.changeset/curvy-lemons-breathe.md, packages/react-client/src/index.ts, packages/react-client/src/lib/callQueryClientFetchMethod.ts, packages/react-client/src/qraftAPIClient.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/create-api-client.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/getClientFactory.ts, website/docs/codegen/create-api-client-function.mdx
- Support for calling `qraftAPIClient(...)` with `{ queryClient }`, enabling non-fetching actions like `resetQueries()`.
- Ensures that `queryFn` is not created when `requestFn` is provided in `callQueryClientMethodWithQueryKey(...)`, avoiding unnecessary fetch logic.
=> feat: add support for non-fetching actions with `qraftAPIClient(...)` using `{ queryClient }`

.changeset/two-lions-burn.md, .changeset/witty-cobras-kiss.md, e2e/projects/typescript-commonjs-node/package.json, packages/react-client/rollup.config.mjs, packages/tanstack-query-react-plugin/src/__snapshots__/operation-predefined-parameters/create-predefined-parameters-request-fn.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/getCreatePredefinedParametersRequestFnFactory.ts
- Added `src/qraftPredefinedParametersRequestFn.ts` as an entry point to Rollup.
- Added `--operation-predefined-parameters` option usage to `typescript-commonjs-node` e2e test case.
- Use `import type` for types in generated `qraftPredefinedParametersRequestFn`.
=> fix(react-client): add missing dist file for `qraftPredefinedParametersRequestFn`

.changeset/hip-ducks-love.md, packages/react-client/src/lib/requestFn.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx
Enhanced the `RequestFnResponse` type in the `@openapi-qraft/react` package to enforce stricter typing.
=> fix(react-client): enforce stricter typing for `RequestFnResponse`

.changeset/good-lizards-grow.md, packages/react-client/src/service-operation/ServiceOperationUseInfiniteQuery.ts, packages/react-client/src/service-operation/ServiceOperationUseSuspenseInfiniteQuery.ts, packages/react-client/src/service-operation/ServiceOperationUseSuspenseQuery.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx
Refined the parameter types for both `useSuspenseInfiniteQuery(...)` and `useSuspenseQuery(...)` in the `react-client` package.
=> chore(react-client): improve parameter types for `useSuspenseInfiniteQuery(...)` and `useSuspenseQuery(...)`

.changeset/good-eagles-help.md, .github/actions/spelling/expect.txt, packages/plugin/src/lib/open-api/getOperationName.spec.ts, packages/plugin/src/lib/open-api/getOperationName.ts, packages/plugin/src/lib/open-api/getServiceName.spec.ts, packages/plugin/src/lib/open-api/getServices.ts
1. Operation names now include all path parts and parameters.
2. The `/api/v{api-version}` part of the path is now retained in the operation name.
3. The `--service-name-base` option is now taken into account when generating operation names.
- The structure of generated operation names has changed, which may affect existing code that relies on the previous naming convention.
- `/api/v{api-version}` is no longer automatically removed from the path when generating names.
- The `--service-name-base` option now influences the generated operation name.
Here are examples of how operation names are now generated based on different `--service-name-base` options:
1. With `--service-name-base=endpoint[0]`:
```
POST /api/v1/users/{id} → postApiV1UsersId
```
2. With `--service-name-base=tags`:
``` …
```
=> feat(plugin): generate comprehensive operation names with service name base option

.changeset/good-eagles-help.md, packages/plugin/src/lib/open-api/getOperationName.spec.ts, packages/plugin/src/lib/open-api/getOperationName.ts, packages/plugin/src/lib/open-api/getServiceName.spec.ts, website/docs/codegen/CLI/cli.mdx
1. Operation names now include all path parts and parameters by default.
2. The `/api/v{api-version}` part of the path is retained in the operation name.
3. The `--service-name-base` option now generates operation names with a new structure, allowing more flexibility and customization.
- The structure of generated operation names has changed, potentially affecting existing code that relies on the previous naming convention.
- `/api/v{api-version}` is no longer automatically removed from the path when generating operation names.
- The `--service-name-base` option now influences the generated operation names.
Here are examples of how operation names are now generated based on different `--service-name-base` options:
1. With `--service-name-base=endpoint[0]`:
```
POST /v1/users/{id} → …
```
=> feat(plugin): update operation name generation 🧁

.changeset/sweet-fans-arrive.md, packages/plugin/src/index.ts, packages/plugin/src/lib/open-api/__snapshots__/getServices.spec.ts.snap, packages/plugin/src/lib/open-api/getServices.ts, packages/react-client/package.json, packages/react-client/rollup.config.mjs, packages/react-client/src/lib/requestFn.ts, packages/react-client/src/lib/responseUtils.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx, packages/react-client/src/unstable__responseUtils.ts, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/getServiceFactory.ts, packages/tanstack-query-react-types/src/shared/MutationFilters.ts, packages/tanstack-query-react-types/src/shared/RequestFn.ts
- If an endpoint is configured to accept different types of input, such as `application/json` or `multipart/form-data`, the generated types will now include representations for all specified formats.
- Added support for JSON and `*/form-data` in the type generation process.
=> feat(react-client): add support for multiple media types payload

.changeset/neat-kangaroos-rhyme.md, packages/react-client/src/lib/responseUtils.ts
Removed the fallback to `JSON.parse`, ensuring more predictable behavior when dealing with plain text responses.
=> feat(react-client): simplify `processResponse` logic for handling `text/plain` content

.changeset/popular-doors-yell.md, packages/openapi-typescript-plugin/src/__snapshots__/no-extra-options.ts.snapshot.ts, packages/openapi-typescript-plugin/src/__snapshots__/with-explicit-component-enum-exports.ts.snapshot.ts, packages/openapi-typescript-plugin/src/__snapshots__/with-explicit-component-exports.ts.snapshot.ts, packages/openapi-typescript-plugin/src/__snapshots__/with-extra-options.ts.snapshot.ts, packages/plugin/src/lib/open-api/OpenAPISchemaType.ts, packages/plugin/src/lib/open-api/getServices.ts, packages/plugin/src/lib/open-api/replaceRefParametersWithComponent.ts, packages/plugin/src/lib/predefineSchemaParameters.test.ts, packages/plugin/src/lib/predefineSchemaParameters.ts, packages/react-client/package.json, packages/test-fixtures/openapi.json
Added support for operation parameters using `$ref` from OpenAPI `components/parameters`.
=> feat(plugin): add support for operation parameters using `$ref` from OpenAPI `components/parameters`

.changeset/two-timers-jam.md, packages/react-client/src/tests/qraftAPIClient.test.tsx, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/getServiceFactory.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationMutationFn.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationSetQueryData.ts, packages/ts-factory-code-generator/package.json, turbo.json
Added support for operations without arguments when possible, improving flexibility and removing unnecessary parameters. Key changes include:
**Support for `void` argument**:
- Added support for passing `void` to mutation operations.
- Added support for the `undefined` argument in the `setQueryData` method.
=> feat: operations without args when possible

.changeset/tidy-knives-travel.md, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions-d-ts-imports/index.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/index.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/openapi-types-import-path-d-ts/index.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/openapi-types-import-path-ts/index.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/getIndexFactory.ts
Changed the exports from the schema file to include only the essential types: `$defs`, `paths`, `components`, `operations`, `webhooks`. This adjustment improves the development experience by preventing the export of all schema types, which could result in an excessive number of exported types, complicating development and reducing clarity.
This change ensures that only the necessary components are exported, avoiding the clutter that would otherwise arise when using the `--explicit-component-exports` option.
=> feat: export from schema just common types

.changeset/famous-turtles-invent.md, packages/cli/README.md, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions-d-ts-imports/index.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/generateCode.ts, packages/tanstack-query-react-plugin/src/plugin.spec.ts, packages/tanstack-query-react-plugin/src/plugin.ts, packages/tanstack-query-react-plugin/src/ts-factory/getClientFactory.ts, packages/tanstack-query-react-plugin/src/ts-factory/getIndexFactory.ts, packages/tanstack-query-react-plugin/src/ts-factory/getServiceIndexFactory.ts, website/docs/codegen/CLI/cli.mdx
Enhance the existing `--explicit-import-extensions` option by adding support for the `.ts` extension. Previously, only `.js` was allowed, but now projects that require TypeScript imports can explicitly specify the `.ts` extension.
- **Updated Option**: `--explicit-import-extensions [extension]`
- Now supports `.ts` in addition to the default `.js`.
- Useful for projects utilizing TypeScript alongside ECMAScript modules.
=> feat: add support for `--explicit-import-extensions .ts`

.changeset/tender-horses-drop.md, packages/openapi-typescript-plugin/src/lib/createOpenapiTypesImportPath.test.ts, packages/openapi-typescript-plugin/src/lib/createOpenapiTypesImportPath.ts, packages/tanstack-query-react-plugin/src/plugin.spec.ts
Fixed support for the `--explicit-import-extensions .ts` option when using the `openapi-typescript-plugin`.
=> fix: support for `--explicit-import-extensions .ts` when used `openapi-typescript-plugin`

.changeset/thirty-beers-nail.md, packages/react-client/package.json, packages/react-client/src/qraftAPIClient.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx, yarn.lock
Resolved an issue where `createAPIClient({ queryClient })` required options to invoke `getInfiniteQueryKey()`, now enabling it to be called without passing options.
=> fix: allow to call `getInfiniteQueryKey()` without options for `createAPIClient()`

.changeset/dirty-donkeys-watch.md, packages/plugin/src/lib/QraftCommand.ts, packages/plugin/src/lib/processOperationNameModifierOption.test.ts, packages/plugin/src/lib/processOperationNameModifierOption.ts
This PR enhances the behavior of the `--operation-name-modifier` option used for modifying operation names in generated services. If an unused modifier is provided (i.e., it doesn't match any paths or operations during code generation), the plugin will now throw an explicit error to notify the developer.
- Added validation for unused `--operation-name-modifier` options.
- If a modifier is specified but not applied to any operations or paths, an error will be emitted during the generation process.
Previously, unused modifiers might have been ignored silently, leading to potential misconfigurations or unintentional behavior. With this update, the developer is informed immediately, ensuring that all provided modifiers are purposeful and correctly configured.
When running the codegen command: …
=> feat(plugin): emit error for unused `--operation-name-modifier` options

.changeset/swift-rivers-hug.md, packages/plugin/src/lib/QraftCommand.ts, packages/plugin/src/lib/open-api/OpenAPIService.ts, packages/plugin/src/lib/open-api/getServices.ts, packages/plugin/src/lib/parseOperationGlobs.ts, packages/plugin/src/lib/processOperationNameModifierOption.ts, packages/tanstack-query-react-plugin/src/generateCode.ts, packages/tanstack-query-react-plugin/src/lib/createOperationCommonTSDoc.ts, packages/tanstack-query-react-plugin/src/ts-factory/getServiceFactory.ts, packages/tanstack-query-react-plugin/src/ts-factory/getServiceIndexFactory.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createOperationMethodTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseInfiniteQueryOperationTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseIsFetchingOperationTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseIsMutatingOperationTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseMutationOperationTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseMutationStateOperationTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseQueriesOperationTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseQueryOperationTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseSuspenseInfiniteQueryOperationTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/lib/createOperationMethodCallExpressionExampleNode.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/lib/createOperationMethodParametersExampleNodes.ts
Move `Service` and `ServiceOperation` into separate files and rename `Service` to `OpenAPIService`.
=> refactor(227): `Service` and `ServiceOperation` types refactoring

.changeset/pre.json, .changeset/tender-pans-joke.md, packages/openapi-typescript-plugin/package.json, packages/plugin/package.json, packages/tanstack-query-react-plugin/package.json, yarn.lock
Ensure external libraries are declared in `peerDependencies` to prevent conflicts and duplication.
=> fix: `commander` `"peerDependencies"`

.changeset/wise-roses-laugh.md, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationIsMutatingQueries.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationUseIsMutating.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationUseMutation.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationUseMutationState.ts
Enhanced type consistency: now, in addition to the standard errors declared in the OpenAPI Document, all methods and hook-off mutations will also return the `Error` type. This ensures that native JavaScript errors are properly handled, reflecting the actual behavior and improving overall type safety.
=> fix(255): add error type to the on error callback

.changeset/mighty-toys-sort.md, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createOperationMethodTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseQueriesOperationTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseSuspenseQueriesOperationTSDocExample.ts, packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseSuspenseQueryOperationTSDocExample.ts
Added TSDoc `@example` generation for the following hooks:
- `useSuspenseQuery`
- `useSuspenseQueries`
This provides clear usage examples in the generated API client.
=> feat: add TSDoc @example generation for `useSuspenseQuery` and `useSuspenseQueries`

.changeset/long-geckos-compare.md, packages/react-client/src/lib/createRecursiveProxy.ts, packages/react-client/src/qraftAPIClient.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx
- Implemented handling for primitive methods (e.g., `toString`, `toJSON`, etc.) during API client usage.
- Included minor refactors and additional improvements beyond the original issue scope.
=> fix(283): handle Primitive Methods (`toString`, `toJSON`) in API Client

.changeset/smooth-crabs-leave.md, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/getServiceFactory.ts
- Previously, mutation parameter types were generated as `{}`, which allowed passing arbitrary objects to hooks like `use_mutations`.
- Replaced with `Record<string, never>` to enforce stricter type safety when no parameters are expected.
- Prevents accidental usage and improves DX.
```ts
// Before
type PostFilesParameters = {};
// After
type PostFilesParameters = Record<string, never>;
```
=> feat(281): replace `{}` with `Record<string, never>` for empty mutation parameters

.changeset/bumpy-ravens-yawn.md, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/getServiceFactory.ts
Simplified the generated code by replacing inlined `schema` types with references to named types where applicable.
=> refactor: use schema type references instead of inline definitions

.changeset/silver-beds-float.md, packages/react-client/src/tests/createAPIClient.const-parameters.types-test.ts, packages/tanstack-query-react-plugin/package.json, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationGetInfiniteQueryData.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationGetQueryData.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationGetQueryState.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationSetInfiniteQueryData.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationSetQueryData.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationUseInfiniteQuery.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationUseMutation.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationUseQuery.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationUseSuspenseInfiniteQuery.ts, packages/tanstack-query-react-types/src/service-operation/ServiceOperationUseSuspenseQuery.ts, packages/tanstack-query-react-types/src/shared/DeepReadonly.ts, packages/tanstack-query-react-types/src/shared/MutationFilters.ts, packages/tanstack-query-react-types/src/shared/QueryFilters.ts, packages/tanstack-query-react-types/src/shared/ServiceOperationFetchInfiniteQueryOptions.ts, packages/tanstack-query-react-types/src/shared/ServiceOperationFetchQueryOptions.ts, packages/tanstack-query-react-types/src/shared/ServiceOperationMutation.ts, packages/tanstack-query-react-types/src/shared/ServiceOperationQuery.ts, packages/tanstack-query-react-types/src/shared/UseQueryOptionsForUseQueries.ts, packages/tanstack-query-react-types/src/shared/UseQueryOptionsForUseSuspenseQuery.ts, packages/tanstack-query-react-types/src/shared/index.ts, yarn.lock
Previously, calling methods like `setQueryData()` with `as const` objects would result in a type error:
```ts
const parameters = {
query: { id__in: ['1', '2'] },
header: { 'x-version': '2' },
} as const;
const data = { query: { id__in: ['1'] } } as const;
qraft.files.getFiles.setQueryData(parameters, data); // ❌ Type error
```
This PR improves developer experience by allowing read-only (immutable) query, body, and headers objects to be passed into such methods without the need for explicit type casting.
=> feat: allow read-only objects to be passed as query or body parameters

.changeset/great-chefs-lie.md, packages/react-client/src/callbacks/useMutation.ts, packages/react-client/src/callbacks/useQueries.ts, packages/react-client/src/callbacks/useSuspenseQueries.ts, packages/react-client/src/lib/callQueryClientFetchMethod.ts, packages/react-client/src/lib/requestFn.test.ts, packages/react-client/src/lib/requestFnResponseRejecter.test.ts, packages/react-client/src/lib/requestFnResponseRejecter.ts, packages/react-client/src/lib/useComposeUseQueryOptions.ts, packages/react-client/src/tests/QraftSecureRequestFn.test.tsx, packages/react-client/tsconfig.json, packages/react-client/vitest.config.ts
This PR fixes error handling issues with `<QraftSecureRequestFn/>` by implementing a dedicated `requestFnResponseRejecter` function to properly handle network errors rather than using the same resolver for both success and error paths.
=> fix: add proper error handling for `<QraftSecureRequestFn/>`

.changeset/strong-mugs-fry.md, packages/openapi-typescript-plugin/src/__snapshots__/no-extra-options.ts.snapshot.ts, packages/openapi-typescript-plugin/src/__snapshots__/with-explicit-component-enum-exports.ts.snapshot.ts, packages/openapi-typescript-plugin/src/__snapshots__/with-explicit-component-exports.ts.snapshot.ts, packages/openapi-typescript-plugin/src/__snapshots__/with-extra-options.ts.snapshot.ts, packages/plugin/src/lib/open-api/OpenAPISchemaType.ts, packages/plugin/src/lib/open-api/OpenAPIService.ts, packages/plugin/src/lib/open-api/__snapshots__/getServices.spec.ts.snap, packages/plugin/src/lib/open-api/getContent.ts, packages/plugin/src/lib/open-api/getServices.ts, packages/react-client/src/tests/msw/handlers.ts, packages/react-client/turbo.json, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/queryable-write-operations/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/getServiceFactory.ts, packages/test-fixtures/openapi.json
Now, for both successful and error responses, we generate types for all possible response outcomes.
For instance, if a 204 (No Content) response is possible, we now explicitly generate a type for it
(represented as `undefined` in the generated code) instead of omitting it.
=> fix(204): generate types for empty responses

.changeset/red-mirrors-add.md, .changeset/strong-mugs-fry.md, packages/openapi-typescript-plugin/src/__snapshots__/no-extra-options.ts.snapshot.ts, packages/openapi-typescript-plugin/src/__snapshots__/with-explicit-component-enum-exports.ts.snapshot.ts, packages/openapi-typescript-plugin/src/__snapshots__/with-explicit-component-exports.ts.snapshot.ts, packages/openapi-typescript-plugin/src/__snapshots__/with-extra-options.ts.snapshot.ts, packages/plugin/src/lib/open-api/__snapshots__/getServices.spec.ts.snap, packages/react-client/src/lib/responseUtils.ts, packages/react-client/src/tests/msw/handlers.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx, packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/__snapshots__/queryable-write-operations/services/FilesService.ts.snapshot.ts, packages/tanstack-query-react-plugin/src/ts-factory/getServiceFactory.ts, packages/test-fixtures/openapi.json
Generate `null` type and return `null` data for the empty (204) responses instead of an empty object `{}`.
=> fix(315): handle empty response with `null`

.changeset/old-carpets-repair.md, packages/openapi-typescript-plugin/src/generateSchemaTypes.ts, packages/react-client/redocly.yaml
This PR adds support for the `--enum-values` and `--dedupe-enums` options to enhance enum processing. It enables better control over generated enum values and removes duplicates when applicable.
=> fix: support for `--enum-values` and `--dedupe-enums` options

.changeset/kind-words-wonder.md, .changeset/rare-lobsters-clean.md, .github/workflows/ci.yml, .github/workflows/e2e.yml, e2e/projects/typescript-nodenext-nodenext/src/index.ts, packages/openapi-typescript-plugin/package.json, packages/plugin/package.json, packages/react-client/package.json, packages/react-client/src/callbacks/useSuspenseQueries.ts, packages/react-client/src/lib/callQueryClientMethodWithQueryFilters.ts, packages/react-client/src/lib/useComposeUseQueryOptions.ts, packages/react-client/src/service-operation/ServiceOperationFetchInfiniteQuery.ts, packages/react-client/src/service-operation/ServiceOperationUseSuspenseInfiniteQuery.ts, packages/react-client/src/tests/qraftAPIClient.test.tsx, yarn.lock
**BREAKING CHANGE**: Updated peer dependency for `@tanstack/react-query` to `^5.80.0` in all relevant packages.
The interface `UseSuspenseInfiniteQueryOptions` in `@tanstack/react-query` changed its parameter structure starting from version 5.80.0. Supporting older versions is no longer possible or practical.
- Projects using versions of `@tanstack/react-query` older than `5.80.0` will no longer be compatible.
This change simplifies dependency management and ensures compatibility with the latest features and fixes in TanStack Query.
The main reason for this breaking change is that the interface `UseSuspenseInfiniteQueryOptions` from the `@tanstack/react-query` package has changed. Previously, this interface had six parameters, but its structure was updated in version 5.80.0. Supporting …
=> chore(1.x): update `peerDependency` ⛱︎ require `@tanstack/react-query@^5.80.0` due to interface changes

.changeset/famous-badgers-roll.md, .changeset/light-files-pull.md, .github/actions/spelling/excludes.txt, packages/react-client/src/lib/requestFn.ts, packages/react-client/src/lib/urlSerializer.test.ts
This PR contains two improvements to URL handling in the React client:
- **Fix URL serialization**: Replace `encodeURI` with `encodeURIComponent` to properly handle slash serialization in path parameters
- **Refactor query string handling**: Replace custom `getQueryString` implementation with native `URLSearchParams` for better maintainability
=> fix: improve URL serialization and query string handling

.changeset/calm-facts-swim.md, packages/tanstack-query-react-types/src/shared/RequestFn.ts
Clarify `RequestFnInfo` type by adding missing `readonly` modifiers for consistency and correctness.
=> fix(tanstack-query-react-types): add missing readonly modifiers in RequestFnInfo type

.changeset/ten-monkeys-lie.md, packages/react-client/src/lib/callQueryClientFetchMethod.ts, packages/react-client/src/lib/prepareRequestFnParameters.ts, packages/react-client/src/lib/useComposeUseQueryOptions.ts, packages/react-client/src/tests/msw/handlers.ts, packages/react-client/src/tests/qraftAPIClient.queryable-write-operations.test.tsx
Refactored parameter preparation logic for queryable write operations to correctly handle body parameters in both regular and infinite queries. The update extracts shared logic into a reusable utility and ensures consistent parameter handling across all affected query methods.
- `fetchQuery` - Fixed body parameter extraction
- `fetchInfiniteQuery` - Fixed body parameter merging with pageParam
- `prefetchQuery` - Fixed body parameter extraction  
- `prefetchInfiniteQuery` - Fixed body parameter merging with pageParam
- `ensureQueryData` - Fixed body parameter extraction
- `ensureInfiniteQueryData` - Fixed body parameter merging with pageParam
- `useInfiniteQuery` - Fixed body parameter merging with pageParam
- `useSuspenseQuery` - Fixed body parameter extraction
- …
=> fix(react-client): improve `body` parameter handling in queryable write operations
