- packages/cli/src/lib/open-api/OpenAPISchemaType.ts
- packages/cli/src/lib/open-api/__fixtures__/openapi.json
- packages/cli/src/lib/open-api/__snapshots__/getServices.spec.ts.snap
- packages/cli/src/lib/open-api/getServices.spec.ts
- packages/cli/src/lib/open-api/getServices.ts
- packages/cli/tsconfig.json
Added `getServices(...)` snapshot tests
> chore(cli): add `getServices(...)` tests

- .github/workflows/deploy-gh-pages.yml
- website/docusaurus.config.js
- website/tools/algolia/config.json
Add Algolia search to the documentation website.
> feat(website): enable Algolia search

- .changeset/cuddly-feet-add.md
- packages/cli/src/bin.ts
- packages/cli/src/writeOpenAPIServices.ts
This PR replaces string paths with URL objects to improve path normalization and encoding, ensuring greater security and consistency across the application. Using URL objects also simplifies handling relative and absolute paths and enhances overall code maintainability.
> feat: replace literal paths usage with URL instances

- .changeset/seven-buttons-chew.md
- e2e/bin/build-projects.sh
- e2e/projects/typescript-commonjs-node/.gitignore
- e2e/projects/typescript-commonjs-node/package.json
- e2e/projects/typescript-commonjs-node/src/commonjs-client.cts
- e2e/projects/typescript-commonjs-node/src/index.ts
- e2e/projects/typescript-commonjs-node/tsconfig.json
- e2e/projects/typescript-esm-node-next/.gitignore
- e2e/projects/typescript-esm-node-next/package.json
- e2e/projects/typescript-esm-node-next/src/commonjs-client.cts
- e2e/projects/typescript-esm-node-next/src/esm-client.mts
- e2e/projects/typescript-esm-node-next/src/index.ts
- e2e/projects/typescript-esm-node-next/tsconfig.json
- packages/react-client/package.json
- packages/react-client/src/index.ts
- packages/react-client/tsup.config.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/create-api-client.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/ts-factory/getClientFactory.ts
- playground/package.json
- yarn.lock
Do not bundle dist to maintain compatibility with Next.js Server Actions.
> feat(react-client): no bundle dist

- .changeset/mean-pianos-laugh.md
- .github/actions/spelling/expect.txt
- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .gitignore
- e2e/projects/typescript-commonjs-node/package.json
- e2e/projects/typescript-commonjs-node/src/commonjs-client.cts
- e2e/projects/typescript-commonjs-node/src/index.ts
- e2e/projects/typescript-esm-node-next/package.json
- e2e/projects/typescript-esm-node-next/src/commonjs-client.cts
- e2e/projects/typescript-esm-node-next/src/esm-client.mts
- e2e/projects/typescript-esm-node-next/src/index.ts
- package.json
- packages/cli/package.json
- packages/openapi-typescript-plugin/package.json
- packages/plugin/package.json
- packages/react-client/package.json
- packages/react-client/rollup.config.mjs
- packages/rollup-config/.gitignore
- packages/rollup-config/package.json
- packages/rollup-config/rollup.config.ts
- packages/rollup-config/tsconfig.json
- packages/tanstack-query-react-plugin/package.json
- playground/package.json
- turbo.json
- yarn.lock
Improved compatibility with CommonJS and enhanced type support across various IDEs.
> fix: commonjs support

- .changeset/early-peas-allow.md
- packages/react-client/src/index.ts
ReExport callbacks from the package index.
> feat(revert): export callbacks from the index

- .changeset/wet-melons-tickle.md
- .prettierrc.json
- packages/openapi-typescript-plugin/package.json
- packages/openapi-typescript-plugin/src/generateSchemaTypes.ts
- packages/openapi-typescript-plugin/src/plugin.ts
- packages/plugin/package.json
- playground/package.json
- website/docs/codegen/cli.mdx
- yarn.lock
Updated `openapi-typescript` to `^7.3.0`.
> chore: update `openapi-typescript`

- .changeset/eleven-crews-switch.md
- .changeset/rude-sheep-yell.md
- packages/cli/README.md
- packages/plugin/package.json
- packages/plugin/src/lib/QraftCommand.ts
- packages/plugin/src/lib/__snapshots__/processOperationNameModifierOption.test.ts.snap
- packages/plugin/src/lib/createServicePathMatch.ts
- packages/plugin/src/lib/filterDocumentPaths.ts
- packages/plugin/src/lib/parseOperationGlobs.test.ts
- packages/plugin/src/lib/parseOperationGlobs.ts
- packages/plugin/src/lib/predefineSchemaParameters.test.ts
- packages/plugin/src/lib/predefineSchemaParameters.ts
- packages/plugin/src/lib/processOperationNameModifierOption.test.ts
- packages/plugin/src/lib/processOperationNameModifierOption.ts
- packages/plugin/src/lib/splitCommaSeparatedGlobs.test.ts
- packages/plugin/src/lib/splitCommaSeparatedGlobs.ts
- packages/react-client/package.json
- packages/react-client/src/tests/msw/handlers.ts
- packages/react-client/src/tests/qraftAPIClient.test.tsx
- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/ts-factory/getServiceFactory.ts
- tsconfig.json
- website/docs/codegen/cli.mdx
Added support for the `--operation-predefined-parameters` option to allow changing operation names.
> feat: add support for `--operation-name-modifier` option

- .github/workflows/deploy-gh-pages.yml
- .github/workflows/update-search-engines.yml
Do not skip manually triggered workflows (`workflow_dispatch`).
> chore(devops): no skip manually triggered workflows

- .changeset/lemon-pans-flow.md
- package.json
- packages/cli/package.json
- packages/openapi-typescript-plugin/package.json
- packages/plugin/package.json
- packages/rollup-config/package.json
- packages/tanstack-query-react-plugin/package.json
- yarn.lock
This pull request updates the TypeScript dependency to version 5.5.4. The update brings in the latest TypeScript features and improvements, enhancing type safety and overall code quality.
> feat: update TypeScript

- .changeset/sharp-wolves-nail.md
> chore: fix Changesets

- .changeset/config.json
Set changesets target branch to `versions/1.x`.
> fix: changesets target branch

- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createOperationMethodTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseInfiniteQueryOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseIsFetchingOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseIsMutatingOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseMutationOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseMutationStateOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseQueriesOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseQueryOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseSuspenseInfiniteQueryOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/lib/createOperationMethodCallExpressionExampleNode.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/lib/createOperationMethodExampleNodes.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/lib/createOperationMethodParametersExampleNodes.ts
- website/docs/hooks/useQueries.mdx
- website/docs/hooks/useSuspenseInfiniteQuery.mdx
- website/versioned_docs/version-1.x/hooks/useSuspenseInfiniteQuery.mdx
- extend TSDoc for `useSuspenseInfiniteQuery` hook
- improve existing hooks TSDoc
> chore: extend `useSuspenseInfiniteQuery` TSDoc

- .changeset/lemon-beers-compete.md
- .github/actions/spelling/expect.txt
- packages/cli/README.md
- packages/openapi-typescript-plugin/src/__snapshots__/no-extra-options.ts.snapshot.ts
- packages/openapi-typescript-plugin/src/__snapshots__/with-explicit-component-enum-exports.ts.snapshot.ts
- packages/openapi-typescript-plugin/src/__snapshots__/with-explicit-component-exports.ts.snapshot.ts
- packages/openapi-typescript-plugin/src/__snapshots__/with-extra-options.ts.snapshot.ts
- packages/plugin/src/lib/open-api/OpenAPISchemaType.ts
- packages/plugin/src/lib/open-api/getServices.ts
- packages/plugin/src/lib/open-api/replaceRefParametersWithComponent.ts
- packages/plugin/src/lib/open-api/resolveDocumentLocalRef.spec.ts
- packages/plugin/src/lib/open-api/resolveDocumentLocalRef.ts
- packages/plugin/src/lib/predefineSchemaParameters.ts
- packages/react-client/README.md
- packages/react-client/package.json
- packages/tanstack-query-react-plugin/src/ts-factory/getServiceFactory.ts
- packages/test-fixtures/openapi.json
- website/docs/codegen/CLI/cli.mdx
- website/docs/getting-started/installation.mdx
- website/docs/getting-started/quick-start.mdx
- website/docs/overview.mdx
Added support for `$ref` in `requestBody`.
> feat: add support for `$ref` in `requestBody`

- .changeset/publish.sh
- .github/workflows/release.yml
Disable publishing with `--provenance` for the e2e tests.
> fix: usage of `--provenance` for the e2e tests

- .changeset/publish.sh
- .github/workflows/release.yml
`--provenance` flag is not supported by Yarn 😭
> chore: disable provenance support in GitHub Actions

- .changeset/cyan-poems-draw.md
- packages/react-client/src/tests/createAPIClient.const-parameters.types-test.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseInfiniteQueryOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseIsFetchingOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseMutationOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createUseSuspenseInfiniteQueryOperationTSDocExample.ts
- packages/tanstack-query-react-types/src/service-operation/ServiceOperationFetchInfiniteQuery.ts
- packages/tanstack-query-react-types/src/service-operation/ServiceOperationUseInfiniteQuery.ts
- packages/tanstack-query-react-types/src/service-operation/ServiceOperationUseSuspenseInfiniteQuery.ts
- packages/tanstack-query-react-types/src/shared/ServiceOperationFetchInfiniteQueryOptions.ts
- packages/tanstack-query-react-types/src/shared/ServiceOperationFetchQueryOptions.ts
Allow the use of fetch* query methods without optional parameters when appropriate.
> feat: Allow the use of fetch* query methods without optional parameters when appropriate

- .changeset/pre.json
- .changeset/yummy-files-relax.md
- packages/react-client/src/tests/qraftAPIClient.test.tsx
- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/queryable-write-operations/services/ApprovalPoliciesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/queryable-write-operations/services/FilesService.ts.snapshot.ts
- packages/tanstack-query-react-types/src/service-operation/ServiceOperationMutationFn.ts
- packages/tanstack-query-react-types/src/shared/ServiceOperationMutation.ts
Added support for `meta` and `signal` for mutating operations.
> feat: add meta and signal for the mutations

- .changeset/bumpy-ads-tie.md
- .changeset/getMutationCache-exact-false-default.md
- packages/react-client/src/callbacks/getMutationCache.ts
- packages/react-client/src/callbacks/index.ts
- packages/react-client/src/lib/composeMutationFilters.ts
- packages/react-client/src/tests/composeMutationFilters.test.ts
- packages/react-client/src/tests/qraftAPIClient.test.tsx
- packages/tanstack-query-react-plugin/generate-ts-factory.mjs
- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/override-import-type/services/ApprovalPoliciesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/queryable-write-operations/services/ApprovalPoliciesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/queryable-write-operations/services/FilesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/ts-factory/serviceOperationNodes.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createGetMutationCacheOperationTSDocExample.ts
- packages/tanstack-query-react-plugin/src/ts-factory/tsdoc/createOperationMethodTSDocExample.ts
- packages/tanstack-query-react-types/src/service-operation/ServiceOperationGetMutationCache.ts
- packages/tanstack-query-react-types/src/service-operation/index.ts
- website/docs/query-client/getMutationCache.mdx
Added `QueryClient.getMutationCache()` method support.
> feat(react-client): add `getMutationCache()` support

- .changeset/silver-rings-mate.md
- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/ApprovalPoliciesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/explicit-import-extensions/services/FilesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/override-import-type/services/ApprovalPoliciesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/queryable-write-operations/services/ApprovalPoliciesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/__snapshots__/queryable-write-operations/services/FilesService.ts.snapshot.ts
- packages/tanstack-query-react-plugin/src/ts-factory/serviceOperationNodes.ts
Grouped service operation methods by functionality for better code organization and readability.
> feat: improve service methods organization in generated files
